### v1
GET http://localhost:8080/v1/users/1/email

### v2
GET http://localhost:8080/v2/users/1/email

### v3
GET http://localhost:8080/v3/users/1/email

### v4
GET http://localhost:8080/v4/users/1/email


