spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: spring
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
